---
apiVersion: v1
kind: Service
metadata:
  name: sample-svc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    project: project
    provider: provider
    group: group
  type: NodePort
