apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: standard
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
- apiVersion: v1
  kind: DeploymentConfig
# Enable when merged with init-container fix:
#  spec:
#    template:
#      metadata:
#        annotations:
#         pod.alpha.kubernetes.io/init-containers: "@assertThat(nullValue())@"