apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
- apiVersion: v1
  kind: PersistentVolumeClaim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi