# We use Travis for the following tasks:
# - Updating the Sonarqube stats when not on a PR
# - Update Codecov (codecov.io) stats for every build
# - Regenerate the docs when commit on master (but not for a PR)
language: java
jdk:
  - oraclejdk8
script:
  # Profile jacoco switches on jacoco coverages
  - mvn test -B -Pjacoco
after_success:
  # Update codecov site. See https://codecov.io/gh/fabric8io/fabric8-maven-plugin
  # Also look into .codecov.yml for configuraton of codecov
  - bash <(curl -s https://codecov.io/bash)
after_script:
  # Update our sonar instalation at https://sonarqube.com/dashboard?id=io.fabric8%3Afabric8-maven-plugin-build
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn -Pjacoco package sonar:sonar -Dsonar.host .url=https://sonarqube.com -Dsonar.login=${SONARQUBE_TOKEN}; else true; fi

