apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: cheese
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
- apiVersion: extensions/v1beta1
  kind: Deployment
  spec:
    template:
      metadata:
        annotations:
          pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"fmp-volume-permission","command":["chmod","777","/var/lib/registry"],"volumeMounts":[{"mountPath":"/var/lib/registry","name":"fabric8-docker-registry-storage"}]}]'
