apiVersion: v1
kind: List
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  spec:
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"fmp-volume-permission","command":["chmod","777","/var/lib/registry"],"volumeMounts":[{"mountPath":"/var/lib/registry","name":"fabric8-docker-registry-storage"}]}]'
